# Gaussian Mixture Model

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
pd.set_option("display.float_format", lambda x: '%.2f' % x)
np.set_printoptions(suppress=True, precision=10)

from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

import optuna

## Ler Dados

In [2]:
df_clientes = pd.read_csv("./dataset/dataset-empresas.csv")
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   atividade_economica     500 non-null    str
 1   faturamento_mensal      500 non-null    float64
 2   numero_de_funcionarios  500 non-null    int64
 3   localizacao             500 non-null    str
 4   idade                   500 non-null    int64
 5   inovacao                500 non-null    int64
dtypes: float64(1), int64(3), str(2)
memory usage: 23.6 KB

In [3]:
df_clientes.describe()

       faturamento_mensal  numero_de_funcionarios  idade  inovacao
count              500.00                  500.00 500.00    500.00
mean           1026715.63                   13.69   9.25      4.39
std             420609.46                    3.12   2.96      2.90
min              18421.22                    2.00   0.00      0.00
25%             763253.58                   12.00   7.00      2.00
50%            1022957.08                   14.00   9.00      4.00
75%            1295888.52                   16.00  11.00      7.00
max            2390677.22                   21.00  16.00      9.00

In [4]:
df_clientes.head()

,atividade_economica,faturamento_mensal,numero_de_funcionarios,localizacao,idade,inovacao
0,Comércio,713109.95,12,Rio de Janeiro,6,1
1,Comércio,790714.38,9,São Paulo,15,0
2,Comércio,1197239.33,17,São Paulo,4,9
3,Indústria,449185.78,15,São Paulo,6,0
4,Agronegócio,1006373.16,15,São Paulo,15,8

## Preparação dos Dados