# Random Forest - Classificação de Churn

In [8]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

import plotly.express as px

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay, \
                            log_loss, roc_curve, roc_auc_score, f1_score, precision_score
import optuna

## Ler Dados

In [9]:
df_churn = pd.read_csv(
  "./dataset/churn.csv",
  parse_dates=['data_contratacao', 'data_demissao', 'data_ultimo_feedback', 'data_ultimo_aumento', 'data_ultima_mudanca_cargo'],
  date_format='%Y-%m-%d'
)
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         2000 non-null   object
 1   idade                      2000 non-null   int64
 2   genero                     2000 non-null   object
 3   estado_civil               2000 non-null   object
 4   educacao                   2000 non-null   object
 5   regime_trabalho            2000 non-null   object
 6   data_contratacao           2000 non-null   datetime64[ns]
 7   data_demissao              286 non-null    datetime64[ns]
 8   tipo_demissao              286 non-null    object
 9   cargo                      2000 non-null   object
 10  salario_atual              2000 non-null   int64
 11  data_ultimo_feedback       2000 non-null   datetime64[ns]
 12  data_ultimo_aumento        2000 non-null   datetime64[ns]
 13  data_ultima_mudanca_cargo  2000 non-null   datetime64[ns]
 14  nota_avaliacao             2000 non-null   float64
 15  acompanhamento_psicologo   2000 non-null   bool
 16  qtde_projetos              2000 non-null   int64
 17  qtde_clientes              2000 non-null   int64
 18  nivel_satisfacao_gestor    2000 non-null   float64
 19  churn                      2000 non-null   int64
dtypes: bool(1), datetime64[ns](5), float64(2), int64(5), object(7)
memory usage: 299.0+ KB

In [10]:
df_churn.head(10)

,id,idade,genero,estado_civil,educacao,regime_trabalho,data_contratacao,data_demissao,tipo_demissao,cargo,salario_atual,data_ultimo_feedback,data_ultimo_aumento,data_ultima_mudanca_cargo,nota_avaliacao,acompanhamento_psicologo,qtde_projetos,qtde_clientes,nivel_satisfacao_gestor,churn
0,EMP1564,37,F,Divorciado(a),Master,Remoto,2020-01-02,NaT,NaN,Senior Developer,10207,2024-05-09,2023-07-31,2022-11-03,9.6,True,5,1,7.0,0
1,EMP0959,45,Outro,Divorciado(a),Master,Remoto,2020-01-03,NaT,NaN,UX Designer,23921,2024-04-05,2023-09-10,2022-02-11,8.4,True,8,4,9.1,0
2,EMP0494,54,M,Viúvo(a),Technical Degree,Híbrido,2020-01-04,NaT,NaN,Tech Lead,15298,2023-06-16,2021-12-26,2021-05-10,8.5,False,9,7,1.3,0
3,EMP1231,44,M,Casado(a),Bachelor,Remoto,2020-01-05,NaT,NaN,QA Engineer,15306,2021-12-04,2022-01-01,2024-08-30,7.9,False,8,4,8.4,0
4,EMP1912,53,Outro,Viúvo(a),PhD,Presencial,2020-01-07,NaT,NaN,Senior Developer,17723,2022-03-04,2023-11-18,2024-08-08,7.5,True,5,2,8.2,0
5,EMP1053,49,Outro,Casado(a),Technical Degree,Híbrido,2020-01-08,NaT,NaN,Junior Developer,6507,2022-06-01,2020-07-05,2021-09-02,7.9,True,8,4,7.1,0
6,EMP1152,29,M,Casado(a),PhD,Presencial,2020-01-10,2022-08-22,Involuntária,Product Manager,12575,2020-10-16,2020-08-11,2022-02-27,9.1,True,6,3,1.9,1
7,EMP1317,38,F,Viúvo(a),PhD,Remoto,2020-01-11,NaT,NaN,DevOps Engineer,16643,2023-03-28,2023-05-16,2022-03-28,8.9,False,6,4,8.3,0
8,EMP1398,33,M,Casado(a),Technical Degree,Remoto,2020-01-12,NaT,NaN,DevOps Engineer,16771,2024-01-03,2024-03-13,2024-06-15,7.6,False,8,1,1.2,0
9,EMP0167,23,M,Viúvo(a),PhD,Híbrido,2020-01-13,NaT,NaN,QA Engineer,13258,2022-01-02,2021-09-15,2024-04-04,8.1,True,3,6,7.0,0

## Engenharia de Features

### Criar features baseadas em datas
- Considerar feedbacks até a data de hoje.
- Features:
    1. Tempo de Empresa.
    2. Dias desde último feedback.
    3. Dias desde última mudança de feedback.
    4. Dias desde último aumento.

In [15]:
df_churn['tempo_empresa'] = df_churn.apply(lambda x: 
                                           (pd.Timestamp.now() - x['data_contratacao']).days
                                           if x['churn'] == 0
                                           else (x['data_demissao'] - x['data_contratacao']).days, axis=1)

In [ ]:
df_churn['dias_ultimo_feedback'] = (pd.Timestamp.now() - df_churn['data_ultimo_feedback']).dt.days

In [32]:
df_churn['dias_ultimo_aumento'] = (pd.Timestamp.now() - df_churn['data_ultimo_aumento']).dt.days

In [33]:
df_churn['dias_ultima_mudanca_cargo'] = (pd.Timestamp.now() - df_churn['data_ultima_mudanca_cargo']).dt.days

In [34]:
df_churn.head(10)

,id,idade,genero,estado_civil,educacao,regime_trabalho,data_contratacao,data_demissao,tipo_demissao,cargo,...,nota_avaliacao,acompanhamento_psicologo,qtde_projetos,qtde_clientes,nivel_satisfacao_gestor,churn,tempo_empresa,dias_ultimo_feedback,dias_ultimo_aumento,dias_ultima_mudanca_cargo
0,EMP1564,37,F,Divorciado(a),Master,Remoto,2020-01-02,NaT,NaN,Senior Developer,...,9.6,True,5,1,7.0,0,2411,822,1105,1375
1,EMP0959,45,Outro,Divorciado(a),Master,Remoto,2020-01-03,NaT,NaN,UX Designer,...,8.4,True,8,4,9.1,0,2410,856,1064,1640
2,EMP0494,54,M,Viúvo(a),Technical Degree,Híbrido,2020-01-04,NaT,NaN,Tech Lead,...,8.5,False,9,7,1.3,0,2409,1150,1687,1917
3,EMP1231,44,M,Casado(a),Bachelor,Remoto,2020-01-05,NaT,NaN,QA Engineer,...,7.9,False,8,4,8.4,0,2408,1709,1681,709
4,EMP1912,53,Outro,Viúvo(a),PhD,Presencial,2020-01-07,NaT,NaN,Senior Developer,...,7.5,True,5,2,8.2,0,2406,1619,995,731
5,EMP1053,49,Outro,Casado(a),Technical Degree,Híbrido,2020-01-08,NaT,NaN,Junior Developer,...,7.9,True,8,4,7.1,0,2405,1530,2226,1802
6,EMP1152,29,M,Casado(a),PhD,Presencial,2020-01-10,2022-08-22,Involuntária,Product Manager,...,9.1,True,6,3,1.9,1,955,2123,2189,1624
7,EMP1317,38,F,Viúvo(a),PhD,Remoto,2020-01-11,NaT,NaN,DevOps Engineer,...,8.9,False,6,4,8.3,0,2402,1230,1181,1595
8,EMP1398,33,M,Casado(a),Technical Degree,Remoto,2020-01-12,NaT,NaN,DevOps Engineer,...,7.6,False,8,1,1.2,0,2401,949,879,785
9,EMP0167,23,M,Viúvo(a),PhD,Híbrido,2020-01-13,NaT,NaN,QA Engineer,...,8.1,True,3,6,7.0,0,2400,1680,1789,857

## EDA